import Head from "next/head";
import { Inter } from "next/font/google";
import { Button, createStyles } from "@mantine/core";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

const useStyles = createStyles((theme) => ({
  root: {
    width: "100%",
    justifyContent: "space-around",
    backgroundColor: "black",
  },
  icon: {},
  iconBox: {},
  heading: {
    color: theme.primaryColor,
  },
}));

//'flexCenter' `flexCenter ${classes.root}`

export default function Home() {
  const { classes, cx, theme } = useStyles();
  // TODO: find override css class with class!
  return (
    <>
      <Head>
        <title>What's Your Poison?</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
      </Head>
      <div className={`${classes.root} flexCenter`}>
        <h1 className={classes.heading}>i'm back!!!</h1>
        <Button
          variant={"gradient"}
          component={Link}
          href='/testingPage'>
          Go to testing
        </Button>
      </div>
    </>
  );
}

// after all imports
// const useStyles = createStyles((theme)=>({

// }))
// before return
// const {classes} = useStyles();
