import Head from "next/head";
import { Inter } from "next/font/google";
import classes from "@/styles/Home.module.css";
import { IconSquareRoundedArrowRight } from "@tabler/icons-react";
import { createStyles } from "@mantine/core";
import Layout from "@/components/layout/Layout";

const inter = Inter({ subsets: ["latin"] });

const useStyles = createStyles((theme) => ({
  root: {
    width: "50%",
  },
  icon: {},
  iconBox: {},
  heading: {
    color: theme.primaryColor,
  },
}));

export default function Home() {
  const { classes } = useStyles();
  return (
    <>
      <Head>
        <title>What's Your Poison?</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
      </Head>
      <div className={classes.root}>
        <h1 className={classes.heading}>i'm back!!!</h1>
      </div>
    </>
  );
}

// after all imports
// const useStyles = createStyles((theme)=>({

// }))
// before return
// const {classes} = useStyles();
